---
version: 2.1
common-steps:
  - &installdeps
    run:
      name: Install Debian packaging dependencies
      command: |
        apt-get update && apt-get install -y gpg
jobs:
  check-sigs:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - *installdeps
      - run:
          name: Verify signatures on all Release files
          command: |
            gpg --import repo/public/fpf-apt-tools-archive-keyring.gpg
            for i in repo/public/dists/*/Release; do gpg --verify "${i}.gpg" "$i"; done
workflows:
  check-packages:
    jobs:
      - check-sigs
