#!/bin/bash
# Script to add a version from the dangerzone repository, by
# copying the debian file to the bookworm folder and creating
# symlinks for it.

set -e
set -x
set -o pipefail

VERSION=$(cat ~dz/dangerzone/share/version.txt)
PACKAGE=dangerzone_${VERSION}-1_amd64.deb

cp ~dz/dangerzone/deb_dist/${PACKAGE} dangerzone/bookworm/${PACKAGE}

for dir in dangerzone/* ; do                                                     
    if [ "$dir" != "dangerzone/bookworm" ]; then                                 
        ln -sf "../bookworm/$PACKAGE" "$dir/."                          
    fi                                                                 
done       
